version: "3.3"

services:
  web:
    restart: always
    build: .
    command: /bin/sh -c /code/entrypoint.prod.sh
    volumes:
      - static_volume:/code/static
    expose:
      - 8015
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - reverseproxy_proxynet

  nginx:
    image: nginx:latest
    restart: always
    hostname: pcr-test.dataekspeditioner.dk
    volumes:
      - static_volume:/code/static
      - type: bind
        source: ./nginx_config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    expose:
      - 1367
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=pcr-test.dataekspeditioner.dk
      - VIRTUAL_PORT=1367
      - LETSENCRYPT_HOST=pcr-test.dataekspeditioner.dk
      - LETSENCRYPT_EMAIL=kmollerschmidt@gmail.com
      - url=https://pcr-test.dataekspeditioner.dk
    networks:
      - reverseproxy_proxynet

  db:
    image: postgres:14
    restart: always
    volumes:
     - database_volume:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - .env.prod
    user: postgres:postgres
    networks:
      - reverseproxy_proxynet


volumes:
  database_volume: {}
  static_volume: {}


networks:
  reverseproxy_proxynet:
    external: true