# Generated by Django 3.2.9 on 2021-11-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcrtest', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pcrtest.city'),
        ),
    ]
