# Generated by Django 3.2.9 on 2021-11-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcrtest', '0004_customer_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
