# Generated by Django 3.2.9 on 2021-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrtest', '0005_alter_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='size',
            field=models.IntegerField(max_length=50),
        ),
    ]
