# Generated by Django 3.2.9 on 2021-11-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcrtest', '0006_alter_city_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='size',
            field=models.IntegerField(),
        ),
    ]
