# Generated by Django 3.2.9 on 2021-12-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcrtest', '0007_alter_city_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
